###consul服务端口号
server:
  port: 81

spring:
  application:
    name: cloud-consumer-order
####consul注册中心地址
  cloud:
    consul:
      host: 192.168.63.130
      port: 8500
      discovery:
        hostname: 172.16.0.201  # 本机的ip地址
        service-name: ${spring.application.name}
